### ISSUE TITLE
Not able to use helm install

### ISSUE THREAD

**Issue by SofiaTa** [nimrodshn/unleash-helm#1]
HI,

Im trying to use the helm chart to install unleash on K8S
(I have running cluster) with the following steps:

1.  clone the repo
2. cd unleash-helm
3. helm install .

the 3 command return error: 
Error: release flippant-heron failed: Service "flippant-heron-postgresql" is invalid: spec.clusterIP: Invalid value: "10.96.0.2": provided IP is not in the valid range. The range of valid IPs is 100.64.0.0/13
 any idea how to overcome this?  why I need the cluster IP and if I can remove it from the values.yaml

**Comment by nimrodshn** [comment]
@SofiaTa Hey! Thanks for reaching out.
The helm charts deploys a postgresql service and pod alongside unleash for it to use.
Unfourtenatly I am not sure how to pass the values from outside the values file (e.g. helm command?) so that they are not **cluster specific**.

~~I think your'e best bet is to edit the `values.yaml` file to something suited to you're cluster~~ - possibly `100.64.0.1`?

See later comment.

Cheers.

**Comment by nimrodshn** [comment]
@SofiaTa turns out you can use the `--set` flag to set the values correctly without needing to edit the values.yaml file. (See https://github.com/helm/helm/blob/master/docs/chart_best_practices/values.md#consider-how-users-will-use-your-values)

So simply run:
```
helm install --set postgresql.service.clusterIP=100.64.0.1 .
```

**Comment by SofiaTa** [comment]
Thanks! I was able to run it :) my question is why I need to provide this clusterIP explicitly? why we need it ? is there a way to avoid it since if I want to deploy is in the second time I got error that it alreay in use, I want to avoid it as much is we can ...

**Comment by nimrodshn** [comment]
Good question! To avoid it we would need to get the inner cluster address space - and pick one from that address space.
Possibly @cben can help?

**Comment by nimrodshn** [comment]
@SofiaTa From [this SO question](https://stackoverflow.com/questions/44190607/how-do-you-find-the-cluster-service-cidr-of-a-kubernetes-cluster) we could retrieve the cluster ip address space using the following command:
```
kubectl cluster-info dump | grep -m 1 service-cluster-ip-range
```

And then generate an address in that space and plug it in. Sounds a little complicated but I will try and add it in as soon as possible. 

If you would like to make a PR that would be very helpful as well ;)

**Comment by SofiaTa** [comment]
@nimrodshn looking forward for this change. sorry but I dont think that I can help here as im not expert on this domain yet :( , thank you!
